/* FortiMune 7.3: current workflow, period accounting and optional mail draft. */
const icon73=path=>`<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
const ICONS73={registered:icon73('<path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15h4"/>'),distributed:icon73('<circle cx="9" cy="7" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3M16 8h5m-2-2 2 2-2 2"/>'),working:icon73('<circle cx="12" cy="12" r="3"/><path d="m9 3 6 0 1 3 3 1 2 5-2 4-3 1-1 4H9l-1-4-3-1-2-4 2-5 3-1z"/>'),injected:icon73('<path d="m14 4 6 6M17 1l6 6M16 6 4 18l2 2L18 8M4 18l-3 5M10 12l2 2"/>'),acknowledged:icon73('<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6zM8 12l3 3 5-6"/>')};
const PHASES73=[['registered','تسجيل الطلب',ICONS73.registered],['distributed','تم التوزيع',ICONS73.distributed],['working','قيد التنفيذ',ICONS73.working],['injected','تم الحقن',ICONS73.injected],['acknowledged','تم الاعتماد والإغلاق',ICONS73.acknowledged]];
function phase73(r){return r.balanceDeductedAt||r.reportAcknowledgement71==='approved'?4:({pending:0,approved:1,assigned:1,in_progress:2,done:3}[r.status]??0)}
function status73(r){return ['rejected','cancelled'].includes(r.status)?'rejected':['postponed','not_executed'].includes(r.status)?'held':r.status==='approval'?'approval':PHASES73[phase73(r)][0]}
function statusLabel73(r){return r.status==='approval'?'مطلوب موافقة دكتور سيد':r.status==='approved'?'جاهز للتوزيع':['rejected','cancelled'].includes(r.status)?'مرفوض / ملغى':['postponed','not_executed'].includes(r.status)?'مؤجل / إيقاف':PHASES73[phase73(r)][1]}
requestProgress=function(r){const current=phase73(r);return `<div class="phases73" aria-label="مراحل الدفعة">${PHASES73.map(([k,label,icon],i)=>{if(r.status==='approved'&&i===1)label='جاهز للتوزيع';return `<span class="phase73 ${k} ${i<=current?'passed':'future'} ${i===current?'current':''}" aria-current="${i===current?'step':'false'}"><i>${i<current?'✓':icon}</i><b>${label}</b></span>`}).join('')}</div>${r.status==='approval'?'<div class="action73 approval">◷ مطلوب موافقة دكتور سيد</div>':pendingReport72(r)?'<div class="action73 approval">◷ بانتظار اعتماد التنفيذ</div>':['rejected','cancelled','postponed','not_executed'].includes(r.status)?`<div class="action73 ${status73(r)}">${statusLabel73(r)} ${esc(r.statusReason||'')}</div>`:''}`};
dailyCards65=function(rows,mode=''){dailyState65();if(!rows.length)return '<p class="card">لا توجد دفعات.</p>';return rows.map(r=>`<details class="daily-card65 status-${status73(r)}" data-owner="${esc(dailyOwner65)}" data-request-id="${esc(r.id)}" ontoggle="rememberDaily65(this)" ${dailyExpanded65.get(r.id)?'open':''}><summary><div class="daily-heading73"><span><b>${esc(r.customerName)}</b><small>${esc(fmtBatchDate(r.batchAt))}</small></span><span class="daily-arrow65" aria-hidden="true"></span></div>${requestProgress(r)}</summary><div class="daily-body65">${requestTable([r],mode)}${!engineering71()?`<button class="ghost" onclick="composeMail73(${attr66(r.id)})">✉ فتح رسالة Outlook</button>`:''}</div></details>`).join('')};
function canAck73(r){return !engineering71()&&((db.ackRights73||[]).includes(r.id)||r.createdByEmployeeId===session.employeeId||isSayed6())}
ackButtons71=function(r){return pendingReport72(r)?`<div class="alert warning">بانتظار اعتماد التنفيذ</div>${canAck73(r)?`<div class="actions"><button class="green save6" onclick="reviewReport71(${attr66(r.id)},true)">✓ اعتماد التنفيذ والإغلاق</button><button class="orange save6" onclick="reviewReport71(${attr66(r.id)},false)">إرجاع التقرير للمراجعة</button></div>`:''}`:''};
VIEWS.reportApprovals71=function(){if(session.role==='engineer')return '';const rows=accessibleRequests().filter(pendingReport72);return title5('','دفعات لم تعتمد','دفعات تم حقنها وتنتظر اعتماد التنفيذ')+rows.map(r=>`<details class="card disclosure67"><summary><b>${esc(r.customerName)} • ${fmtBatchDate(r.batchAt)}</b><span class="arrow67"></span></summary><div class="disclosure-body67">${reportFacts72(r)}${requestProgress(r)}<button class="open-request70" onclick="handleBatchLink68(${attr66(r.id)})">رؤية تقرير الدفعة</button>${ackButtons71(r)}</div></details>`).join('')+(rows.length?'':'<p class="card">لا توجد دفعات بانتظار الاعتماد.</p>')};
const homePrevious73=VIEWS.home;VIEWS.home=function(){const root=document.createElement('div');root.innerHTML=homePrevious73();if(session.role!=='engineer')root.querySelector('.v5-stats')?.insertAdjacentHTML('beforeend',`<button class="v5-stat orange" onclick="go('reportApprovals71')"><span>دفعات لم تعتمد</span><strong>${accessibleRequests().filter(pendingReport72).length}</strong><small>مراجعة واعتماد التنفيذ ←</small></button>`);return root.innerHTML};
let feedbackTimer73;
appMessage=function(message,tone=messageTone(message)){document.querySelectorAll('#appMessages,.feedback73').forEach(el=>el.remove());clearTimeout(feedbackTimer73);const el=document.createElement('div');el.className='feedback73 '+tone;el.dir='rtl';const ok=tone==='success',rejected=tone==='rejected',title=rejected?message:ok?(/^تم/.test(message)?message:'تمت العملية بنجاح'):tone==='error'?'تعذّر تنفيذ العملية':/بانتظار|Approval/.test(message)?'تم إرسال الطلب للموافقة':'تنبيه';el.innerHTML=`<section role="${ok?'status':'alert'}" aria-live="polite"><div class="feedback-symbol73">${ok?'✓':rejected?'×':tone==='error'?'!':'◷'}</div><h3>${esc(title)}</h3><p>${esc(ok?'تم حفظ البيانات بنجاح.':rejected?'تم حفظ قرار الرفض.':message)}</p><button class="${ok?'green':'primary'}">تم</button></section>`;el.querySelector('button').onclick=()=>el.remove();document.body.append(el);feedbackTimer73=setTimeout(()=>el.remove(),ok?3000:6000)};
function reasonDialog73(title,description,confirm='تأكيد',initial=''){return new Promise(resolve=>{if(document.querySelector('#reasonDialog73'))return resolve(null);const previous=document.activeElement,el=document.createElement('div');el.id='reasonDialog73';el.className='app-confirm-overlay';el.dir='rtl';el.innerHTML=`<section class="app-confirm" role="dialog" aria-modal="true" aria-labelledby="reasonTitle73"><h3 id="reasonTitle73">${esc(title)}</h3><p>${esc(description)}</p><label for="reasonText73">السبب *</label><textarea id="reasonText73" maxlength="400">${esc(initial)}</textarea><p class="reason-error73" role="alert"></p><div class="actions"><button class="primary">${esc(confirm)}</button><button class="ghost">إلغاء</button></div></section>`;const finish=v=>{el.remove();previous?.focus();resolve(v)};el.querySelector('.primary').onclick=()=>{const v=el.querySelector('textarea').value.trim();if(v.length<3){el.querySelector('.reason-error73').textContent='اكتب السبب، ٣ أحرف على الأقل.';return}finish(v)};el.querySelector('.ghost').onclick=()=>finish(null);el.onkeydown=e=>{if(e.key==='Escape')finish(null);if(e.key==='Tab'){const a=[...el.querySelectorAll('textarea,button')],first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.body.append(el);el.querySelector('textarea').focus()})}
reviewFinance72=async function(id,approve){if(cloudBusy||!isSayed6())return;const reason=approve?'تمت مراجعة الطلب والموافقة':await reasonDialog73('رفض الطلب المالي','اكتب سبب رفض الفاتورة أو المرتجع.','تأكيد الرفض');if(!reason||approve&&!await appConfirm('الموافقة وتنفيذ الحركة المالية مرة واحدة؟'))return;return call6(approve?'finance_approve72':'finance_reject72',{id,reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},approve?'تمت الموافقة وتنفيذ العملية':'تم رفض الطلب',approve?'success':'rejected')};
reviewReport71=async function(id,approve){if(cloudBusy)return;const r=db.requests.find(x=>x.id===id);if(!r||!canAck73(r))return;const reason=approve?'اعتماد التنفيذ بعد مراجعة التقرير':await reasonDialog73('إرجاع التقرير للمراجعة','اكتب التعديل المطلوب من المهندس.','إرجاع التقرير');if(!reason||approve&&!await appConfirm('اعتماد التنفيذ والإغلاق وخصم الاستهلاك الفعلي من العميل مرة واحدة؟'))return;return call6(approve?'report_ack71':'report_return71',{id,reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},approve?'تم اعتماد التنفيذ والإغلاق':'تم إرجاع التقرير للمراجعة',approve?'success':'warning')};
approveRequest=async function(id){const r=db.requests.find(x=>x.id===id);if(!isSayed6()||cloudBusy||r?.status!=='approval'||!await appConfirm('الموافقة على الدفعة وإرسالها للتوزيع؟'))return;return call6('approve',{id,expectedStatus:'approval',expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تمت الموافقة وإرسال الدفعة للتوزيع')};
rejectRequest=async function(id){if(!isSayed6()||cloudBusy)return;const r=db.requests.find(x=>x.id===id);if(r?.status!=='approval')return;const reason=await reasonDialog73('رفض طلب الحقن','اكتب سبب رفض الدفعة.','تأكيد الرفض');if(reason)return call6('reject',{id,expectedStatus:'approval',reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تم رفض طلب الحقن','rejected')};
reviewCustomer66=async function(id,approve){if(!isSayed6()||cloudBusy)return;const reason=approve?'':await reasonDialog73('رفض إضافة العميل','اكتب سبب الرفض.','تأكيد الرفض');if(reason===null||approve&&!await appConfirm('الموافقة على إضافة العميل؟'))return;return call6(approve?'customer_approve66':'customer_reject66',{id,reason,operationId:crypto.randomUUID()},approve?'تمت الموافقة على إضافة العميل':'تم رفض إضافة العميل',approve?'success':'rejected')};
reviewChange70=async function(id,approve){if(!isSayed6()||cloudBusy)return;const reason=approve?'':await reasonDialog73('رفض تعديل العميل','اكتب سبب الرفض.','تأكيد الرفض');if(reason===null||approve&&!await appConfirm('الموافقة على تعديل بيانات العميل؟'))return;return call6('customer_review70',{id,approve,reason,operationId:crypto.randomUUID()},approve?'تم اعتماد تعديل العميل':'تم رفض التعديل',approve?'success':'rejected')};
settleBatch71=async function(id){if(!isSayed6()||cloudBusy)return;const reason=await reasonDialog73('تسوية فريق الحقن','إضافة الكمية المتاحة للفريق. حساب العميل مستقل.','حفظ التسوية','تعويض الأمبولات المستهلكة للدفعة');if(reason)return call6('team_settle72',{id,reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تم حفظ تسوية فريق الحقن')};
// One visible card per accessible batch; the original server notice ID is retained for mark_read.
const noticesPrevious73=currentNotifications;currentNotifications=function(){const rows=noticesPrevious73(),groups=new Map(),separate=[];for(const n of rows){const r=accessibleRequests().find(r=>r.id===n.requestId);if(!r||/تسوية|عجز|تغطية/.test(n.title||'')){separate.push(n);continue}const prior=groups.get(r.id);if(!prior||String(n.createdAt)>String(prior.createdAt))groups.set(r.id,n)}return [...separate,...[...groups].map(([id,n])=>{const r=db.requests.find(r=>r.id===id);return {...n,title:r.customerName+' — '+statusLabel73(r),type:status73(r),message:pendingReport72(r)?'بانتظار اعتماد التنفيذ':statusLabel73(r)}})]};
// Financial period: opening + opening edits + approved sales - returns - committed consumption.
function financialSummary73(){const d=dashData61(),old={...movementFilter},result=[];try{movementFilter.from=dash61.from;movementFilter.to=dash61.to;for(const p of dashProducts68()){let opening=0,closing=0,adjustment=0,sales=0,returns=0,consumption=0;for(const c of d.customers){opening+=dash61.from?balanceAt69(c,p.id,true):Number((db.customerOpening69||[]).find(x=>x.customerId===c.id&&x.productId===p.id)?.initial??customerOpeningValue66(c,p.id));closing+=balanceAt69(c,p.id);for(const m of db.movements||[]){if(m.customerCode!==c.id||m.productId!==p.id)continue;const date=m.businessDate||cairoDate66(m.date);if(dash61.from&&date<dash61.from||dash61.to&&date>dash61.to)continue;const n=Number(m.change||0);if(m.movementType==='opening_adjustment'||m.movementType==='adjustment')adjustment+=n;else if(m.invoiceId)sales+=n;else if(m.returnId)returns-=n;else if(m.requestId||m.movementType==='consumption'){const r=db.requests.find(r=>r.id===m.requestId);if(!r||r.balanceDeductedAt||!r.flow71&&!r.flow72&&r.settlementModel68!=='on_settlement')consumption-=n;}}}result.push([p.name,opening,adjustment,sales,returns,consumption,closing]);}return result}finally{Object.assign(movementFilter,old)}}
const dashboardPrevious73=VIEWS.dashboard61;VIEWS.dashboard61=function(){const root=document.createElement('div');root.innerHTML=dashboardPrevious73();const d=dashData61();root.querySelectorAll('.v5-stat').forEach(el=>{if(/تم التوزيع|قيد التنفيذ|مؤجلة \/ ملغاة|بيع —|مرتجع —|استهلاك —|الرصيد الحالي —/.test(el.querySelector('span')?.textContent||''))el.remove()});root.querySelectorAll('p.muted').forEach(el=>{if(/الأرصدة هي الحالية/.test(el.textContent))el.textContent='الأرصدة محسوبة حتى نهاية الفترة المختارة. الاستهلاك المالي يُسجّل بعد اعتماد التنفيذ.'});root.querySelectorAll('section.card').forEach(el=>{if(el.querySelector('h3')?.textContent==='بيع وحقن كل صنف خلال الفترة')el.remove()});const actual=d.done.reduce((n,r)=>n+(r.actualItems||[]).filter(i=>!dash61.product||dash61.product==='ALL'||i.productId===dash61.product).reduce((n,i)=>n+Number(i.actualQty||0),0),0);root.querySelector('.v5-stats')?.insertAdjacentHTML('beforeend',`<div class="v5-stat injected"><span>الحقن الفعلي — أمبولات</span><strong>${actual}</strong></div>`);if(!d.engineering&&finRole()){const rows=financialSummary73(),heads=['الصنف','الرصيد الافتتاحي','تعديل الرصيد الافتتاحي','بيع','مرتجع','حقن / استهلاك','الرصيد الحالي'];root.querySelector('.v5-stats')?.insertAdjacentHTML('beforeend',heads.slice(1).map((label,i)=>`<div class="v5-stat blue"><span>${label}</span><strong>${rows.reduce((n,r)=>n+r[i+1],0)}</strong></div>`).join(''));root.insertAdjacentHTML('beforeend',`<section class="card"><h3>أرصدة الأصناف خلال الفترة</h3>${table69(heads,rows)}</section>`)}return root.innerHTML};
const exportDashPrevious73=exportDash61;exportDash61=function(){if(!validRange5(dash61))return;if(!financial71())return exportDashPrevious73();const d=dashData61();downloadExcel5('FortiMune-Dashboard',[{name:'أرصدة الفترة',rows:[['الصنف','الرصيد الافتتاحي','تعديل الرصيد الافتتاحي','بيع','مرتجع','حقن / استهلاك','الرصيد الحالي'],...financialSummary73()]},{name:'الحقن الفعلي',rows:[['الطلب','العميل','التاريخ','الطيور','الصنف','الفعلي'],...d.done.flatMap(r=>(r.actualItems||[]).map(i=>[r.id,r.customerName,dailyDateOnly(r.closedAt),r.actualBatchQty||0,i.productName,i.actualQty]))]}])};
// The mail route is explicitly configured, never inferred from an unverified name.
function mailDraft73(r){const cfg=db.mailRouting73||{},contacts=db.mailContacts73||[],email=id=>contacts.find(c=>c.employeeId===id)?.email||'',sayed=cfg.sayed||email('EMP-015'),walid=cfg.walid||email('EMP-017'),ashraf=cfg.ashraf||'ashraf.mostafa@ift-online.com',c=db.customers.find(c=>c.id===r.customerId),snapshot=r.mailAvailable73||r.mailBalances73||c?.balances||{},items=(r.items||[]).map(i=>({...i,available:Number(snapshot[i.productId]||0),shortage:Math.max(0,Number(i.requestedQty||0)-Math.max(0,Number(snapshot[i.productId]||0)))})),approval=r.status==='approval'||items.some(i=>i.shortage>0),manager=cfg['manager:'+r.region]||'',missing=[!sayed?'إيميل دكتور سيد':'',!walid?'إيميل دكتور وليد':'',!manager?'إيميل المدير المباشر للمنطقة':''].filter(Boolean),url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('request',r.id);const to=approval?sayed:ashraf,cc=[approval?ashraf:sayed,walid,manager].filter(e=>e&&e.toLowerCase()!==to.toLowerCase());return {to,cc:[...new Map(cc.map(e=>[e.toLowerCase(),e])).values()],missing,subject:`${approval?'Approval Required':'Injection Distribution Request'} | ${r.id} | ${r.customerName}`,body:[approval?'مطلوب موافقة على طلب حقن لعدم كفاية رصيد صنف أو أكثر.':'يرجى مراجعة طلب الحقن وتوزيعه.',`رقم الطلب: ${r.id}`,`العميل: ${r.customerName}`,`المزرعة: ${r.farmName||'—'}`,`الدفعة: ${r.batchName||'—'}`,`تاريخ الدفعة: ${r.batchAt}`,`المنطقة: ${r.region}`,`مصدر الأمبولات: ${r.source}`,`المعمل: ${r.lab||'—'}`,`عدد الطيور: ${r.batchQty||r.batchCount||'—'}`,`صاحب الطلب: ${r.createdBy||session.name}`,'الأصناف (المطلوب / المتاح / العجز):',...items.map(i=>`${i.productName||i.productId}: ${i.requestedQty} / ${i.available} / ${i.shortage}`),`رابط الطلب: ${url.href}`,'الموافقة واعتماد التنفيذ يتمان داخل FortiMune.'].join('\n')}}
function composeMail73(id){const r=accessibleRequests().find(r=>r.id===id);if(!r||engineering71())return;const draft=mailDraft73(r),mailto='mailto:'+encodeURIComponent(draft.to)+'?'+new URLSearchParams({cc:draft.cc.join(','),subject:draft.subject,body:draft.body}).toString().replace(/\+/g,'%20'),outlook='https://outlook.office.com/mail/deeplink/compose?'+new URLSearchParams({to:draft.to,cc:draft.cc.join(';'),subject:draft.subject,body:draft.body});document.querySelector('#mailDraft73')?.remove();const el=document.createElement('div');el.id='mailDraft73';el.className='app-confirm-overlay';el.dir='rtl';el.innerHTML=`<section class="app-confirm mail73" role="dialog" aria-modal="true"><h3>رسالة Outlook جاهزة للمراجعة</h3>${draft.missing.length?`<p class="alert warning">إعدادات ناقصة: ${esc(draft.missing.join('، '))}. استكمل المستلمين قبل الإرسال.</p>`:''}<label>إلى</label><p dir="ltr">${esc(draft.to||'يحتاج إعداد')}</p><label>Cc</label><p dir="ltr">${esc(draft.cc.join(', '))}</p><b>${esc(draft.subject)}</b><pre>${esc(draft.body)}</pre><div class="actions"><a class="primary mail-open73" href="${esc(mailto)}">فتح في تطبيق البريد / Outlook</a><a class="ghost" target="_blank" rel="noopener" href="${esc(outlook)}">Outlook على الويب</a><button class="ghost" onclick="document.getElementById('mailDraft73').remove()">إغلاق</button></div><small>راجع المستلمين واضغط إرسال من Outlook. إغلاق الرسالة لا يلغي الدفعة.</small></section>`;document.body.append(el)}
const createPrevious73=createRequest;let creating73=false,requestPending73=null;createRequest=async function(withMail=false){if(creating73||cloudBusy)return;creating73=true;const owner=session?.authUserId,ids=new Set(db.requests.map(r=>r.id));try{await createPrevious73();const created=session?.authUserId===owner?db.requests.find(r=>!ids.has(r.id)&&r.createdByEmployeeId===session.employeeId):null;if(created){requestPending73=null;if(withMail){document.querySelectorAll('.fortimune-result-overlay,.feedback73').forEach(el=>el.remove());composeMail73(created.id)}}}finally{creating73=false}};
const changePayloadPrevious73=changePayload;changePayload=function(operation,id,before){const result=changePayloadPrevious73(operation,id,before);if(operation==='create'&&result){const signature=JSON.stringify([session.authUserId,result.customerId,result.batchAt,result.farmName,result.lab,result.batchQty,result.source,result.items]);if(requestPending73?.signature!==signature)requestPending73={signature,id:result.id,operationId:crypto.randomUUID()};const balances=before.customers.find(c=>c.id===result.customerId)?.balances||{},old=db.requests;let available={};try{db.requests=before.requests;available=Object.fromEntries((result.items||[]).map(i=>[i.productId,Number(balances[i.productId]||0)-getReserved(result.customerId,i.productId)]))}finally{db.requests=old}return {...result,id:requestPending73.id,operationId:requestPending73.operationId,mailBalances73:balances,mailAvailable73:available}};return result};
const newRequestPrevious73=VIEWS.newRequest;VIEWS.newRequest=function(){return newRequestPrevious73().replace(/<button class="primary request-submit" onclick="createRequest\(\)">[\s\S]*?<\/button>/,`<div class="mail-submit73"><button class="primary request-submit" onclick="createRequest(true)">تسجيل طلب الحقن + Outlook ✉</button><button class="ghost request-submit" onclick="createRequest(false)">تسجيل طلب الحقن فقط</button></div>`)};
VIEWS.mailSettings73=function(){if(!isSayed6())return '';const s=db.mailRouting73||{},fields=[['sayed','إيميل دكتور سيد'],['walid','إيميل دكتور وليد'],['ashraf','إيميل أشرف'],...REGIONS.map(x=>['manager:'+x,'المدير المباشر — '+x])];return title5('','مستلمو Outlook','حدد الإيميلات الرسمية للرسائل')+`<section class="card">${fields.map(([k,label])=>`<label>${esc(label)}</label><input type="email" dir="ltr" data-mail-key73="${esc(k)}" value="${esc(s[k]||'')}">`).join('')}<button class="primary save6" onclick="saveMailSettings73()">حفظ إعدادات المستلمين</button></section>`};
async function saveMailSettings73(){const settings=Object.fromEntries([...document.querySelectorAll('[data-mail-key73]')].map(el=>[el.dataset.mailKey73,el.value.trim()]).filter(([,v])=>v));if(Object.values(settings).some(x=>!/^\S+@\S+\.\S+$/.test(x)))return appMessage('راجع الإيميلات','warning');return call6('mail_settings73',{settings,expectedRevision:cloudRevision},'تم حفظ مستلمي Outlook')}
const menuPrevious73=VIEWS.menu61;VIEWS.menu61=function(){return menuPrevious73()+(isSayed6()?tile5('✉','مستلمو Outlook','إيميلات المديرين والمناطق','mailSettings73','blue'):'')};navGroup.mailSettings73='menu61';navGroup.reportApprovals71='requests66';
// Remove superseded customer-settlement wording from the old report layers and exports.
customerSummaryHeads70.splice(0,customerSummaryHeads70.length,'العميل','الصنف','الرصيد الافتتاحي','تعديل الرصيد الافتتاحي','بيع','مرتجع','حقن / استهلاك','الرصيد الحالي');
customerSummary70=function(){return selectedCustomers69().flatMap(c=>PRODUCTS.map(p=>{const rows=(db.movements||[]).filter(m=>m.customerCode===c.id&&m.productId===p.id&&(!movementFilter.from||(m.businessDate||cairoDate66(m.date))>=movementFilter.from)&&(!movementFilter.to||(m.businessDate||cairoDate66(m.date))<=movementFilter.to)),sum=f=>rows.filter(f).reduce((n,m)=>n+Number(m.change||0),0),opening=movementFilter.from?balanceAt69(c,p.id,true):Number((db.customerOpening69||[]).find(x=>x.customerId===c.id&&x.productId===p.id)?.initial??customerOpeningValue66(c,p.id));return [c.name,p.name,opening,sum(m=>['opening_adjustment','adjustment'].includes(m.movementType)),sum(m=>!!m.invoiceId),-sum(m=>!!m.returnId),-sum(m=>!m.invoiceId&&!m.returnId&&!['opening_adjustment','adjustment'].includes(m.movementType)&&(m.requestId||['consumption','team_transfer'].includes(m.movementType))),balanceAt69(c,p.id)]}))};
const movementPrevious73=VIEWS.movement;VIEWS.movement=function(){const root=document.createElement('div');root.innerHTML=movementPrevious73();root.querySelectorAll('p').forEach(el=>{if(/تسوية|عجز/.test(el.textContent))el.remove()});return root.innerHTML};
// Grouping returns presentation copies: read mutations must target original server IDs.
markAllNotificationsRead=function(){const ids=new Set(currentNotifications().filter(n=>!n.readAt).map(n=>n.id));for(const n of db.notifications||[])if(ids.has(n.id)){n.readAt=now();noticeExpanded64.set(n.id,false)}save();renderNotifications();updateNotificationBadge()};
wrapSharedMutation('markAllNotificationsRead','mark_read');
