/* FortiMune 7.4: explicit ampoule ownership, requester execution, engineer performance. */
const SOURCES74=['الشركة','فريق الحقن','رصيد العميل في المعمل','رصيد المعمل نفسه'];
const NO_ENGINEER74=['p5','p6','p7','p8'];
const source74=s=>s==='المعمل'?'رصيد العميل في المعمل':s;
const attendance74=r=>r.withoutEngineer74?'بدون حضور مهندس':'بحضور مهندس';
SOURCES.splice(0,SOURCES.length,...SOURCES74);
let formMode74=false,closing74=false,closeRetry74=null;
const requestView74=VIEWS.newRequest;
VIEWS.newRequest=function(){const root=document.createElement('div');root.innerHTML=requestView74();const source=root.querySelector('#source');if(source){source.innerHTML=(formMode74?SOURCES74.filter(s=>['الشركة','رصيد العميل في المعمل'].includes(s)):SOURCES74).map(s=>`<option>${s}</option>`).join('');source.setAttribute('onchange','updateBalanceBox()')}
 root.querySelector('.request-form-grid')?.insertAdjacentHTML('afterbegin',`<div class="flow-select74"><label>مسار الدفعة</label><select id="withoutEngineer74" onchange="setRequestMode74(this.value==='true')"><option value="false" ${!formMode74?'selected':''}>دفعة بحضور مهندس</option><option value="true" ${formMode74?'selected':''}>دفعة بدون مهندس</option></select><small>${formMode74?'برايمر 5000 و2500 وV4 وأكسنيل — موافقة دكتور سيد ثم صاحب الطلب يرفع التقرير ويغلق.':'توزيع على مهندس ثم مراجعة واعتماد التنفيذ.'}</small></div>`);
 if(formMode74)for(const p of PRODUCTS)if(!NO_ENGINEER74.includes(p.id))root.querySelector('#pi-'+p.id)?.remove();return root.innerHTML};
function setRequestMode74(value){const values=Object.fromEntries(['batchAt','customerId','farmName','lab','batchQty','source'].map(id=>[id,document.getElementById(id)?.value]));const lines=selectedProductLines();formMode74=value;tab='newRequest';render();for(const [id,v]of Object.entries(values)){const el=document.getElementById(id);if(el&&v&&(!(el instanceof HTMLSelectElement)||[...el.options].some(o=>o.value===v)))el.value=v}for(const {product,qty}of lines){const c=document.getElementById('chk-'+product.id),q=document.getElementById('qty-'+product.id);if(c&&q){c.checked=true;q.value=qty;toggleProduct(product.id)}}updateBalanceBox()}
const requestsMenu74=VIEWS.requests66;VIEWS.requests66=function(){return requestsMenu74()+(customerCreate66()?tile5('▤','طلب دفعة بدون مهندس','موافقة دكتور سيد ثم التقرير والإغلاق بواسطة صاحب الطلب','newRequestWithout74','purple'):'')};
VIEWS.newRequestWithout74=function(){formMode74=true;return VIEWS.newRequest()};navGroup.newRequestWithout74='requests66';
const reserved74=getReserved;getReserved=function(customerId,productId,excludeId=null){return db.requests.filter(r=>source74(r.source)!=='رصيد المعمل نفسه'&&r.customerId===customerId&&r.id!==excludeId&&['new','approval','approved','pending','assigned','in_progress','postponed','not_executed'].includes(r.status)).reduce((n,r)=>n+requestItems(r).filter(i=>i.productId===productId).reduce((a,i)=>a+Number(i.requestedQty||0),0),0)};
const balancePreview74=updateBalanceBox;updateBalanceBox=function(){if(document.getElementById('source')?.value==='رصيد المعمل نفسه'){const el=document.getElementById('balanceBox');if(el){el.className='preview success';el.textContent='رصيد المعمل نفسه: نسجل الاستهلاك والتقرير فقط. لا خصم من رصيد العميل أو فريق الحقن، ولا تسوية أو عجز.'}return}balancePreview74();if(formMode74)document.getElementById('balanceBox')?.insertAdjacentHTML('beforeend','<p>موافقة دكتور سيد مطلوبة لهذه الدفعة مهما كان رصيد العميل.</p>')};
createRequest=async function(withMail=false){if(creating73||cloudBusy)return;const c=db.customers.find(c=>c.id===document.getElementById('customerId')?.value);if(!c||!customerIsVisible(c))return appMessage('اختار عميلًا ضمن منطقتك.','warning');const items=selectedProductLines().map(({product,qty})=>({productId:product.id,productName:product.name,requestedQty:qty}));const input={customerId:c.id,batchAt:document.getElementById('batchAt')?.value,farmName:document.getElementById('farmName')?.value.trim(),lab:document.getElementById('lab')?.value.trim(),batchQty:Number(document.getElementById('batchQty')?.value||0),source:document.getElementById('source')?.value,withoutEngineer74:formMode74,items};
 if(!input.batchAt||!input.farmName||!input.lab||!Number.isSafeInteger(input.batchQty)||input.batchQty<1||!items.length||items.some(i=>!Number.isSafeInteger(i.requestedQty)||i.requestedQty<1)||!SOURCES74.includes(input.source))return appMessage('أكمل بيانات الدفعة والأصناف والكميات.','warning');if(formMode74&&(items.some(i=>!NO_ENGINEER74.includes(i.productId))||!['الشركة','رصيد العميل في المعمل'].includes(input.source)))return appMessage('راجع أصناف ومصدر الدفعة بدون مهندس.','warning');
 const signature=JSON.stringify([session.authUserId,input]);if(requestPending73?.signature!==signature)requestPending73={signature,id:'REQ-'+crypto.randomUUID().slice(0,8).toUpperCase(),operationId:crypto.randomUUID()};creating73=true;try{await fetchCloudState();const current=db.customers.find(x=>x.id===c.id);const payload={...input,id:requestPending73.id,operationId:requestPending73.operationId,expectedRevision:cloudRevision,mailBalances73:current?.balances||{},mailAvailable73:Object.fromEntries(items.map(i=>[i.productId,Number(current?.balances?.[i.productId]||0)-getReserved(c.id,i.productId)]))};const ok=await call6('create',payload,formMode74?'تم تسجيل الدفعة وإرسالها لموافقة دكتور سيد':'تم تسجيل طلب الحقن بنجاح',formMode74?'warning':'success');if(ok){const r=db.requests.find(r=>r.id===payload.id);requestPending73=null;tab='home';render();if(r?.status==='approval'){if(r.withoutEngineer74)appMessage('تم تسجيل الدفعة بدون مهندس — بانتظار موافقة دكتور سيد','warning');else showRequestResult(true)};if(withMail&&r){document.querySelectorAll('.feedback73,.fortimune-result-overlay').forEach(e=>e.remove());composeMail73(r.id)}}}catch(e){appMessage(e.message||'تعذر تسجيل الدفعة','error')}finally{creating73=false}};
const block74=executionBlockReason53;executionBlockReason53=function(r){if(!r?.withoutEngineer74)return block74(r);if(r.onHold)return 'الدفعة موقوفة على Hold.';if(r.status==='done')return 'الدفعة مغلقة بالفعل.';if(r.createdByEmployeeId!==session.employeeId||engineering71())return 'رفع التقرير والإغلاق لصاحب الطلب فقط.';if(r.status!=='approved'||r.approvedByEmployeeId!=='EMP-015')return 'موافقة دكتور سيد مطلوبة قبل رفع التقرير والإغلاق.';return ''};
const actions74=actionFor;actionFor=function(r,mode){if(!r.withoutEngineer74)return actions74(r,mode);if(r.status==='approval')return isSayed6()?`<button class="green save6" onclick="approveRequest(${attr66(r.id)})">موافقة</button><button class="red save6" onclick="rejectRequest(${attr66(r.id)})">رفض</button>`:'<span class="badge b-approval">بانتظار موافقة دكتور سيد</span>';if(r.status==='approved')return r.createdByEmployeeId===session.employeeId&&!engineering71()?`<button class="primary" onclick="openClose(${attr66(r.id)})">رفع التقرير وإغلاق الدفعة</button>`:'<span class="badge b-assigned">بانتظار تقرير صاحب الطلب</span>';if(r.status==='done')return `<button class="green" onclick="viewCompletedRequest(${attr66(r.id)})">رؤية تقرير الدفعة</button>`;return actions74(r,mode)};
const approve74=approveRequest;approveRequest=async function(id){const r=db.requests.find(r=>r.id===id);if(!r?.withoutEngineer74)return approve74(id);if(!isSayed6()||cloudBusy||r.status!=='approval'||!await appConfirm('الموافقة وإعادة الدفعة لصاحب الطلب لرفع التقرير والإغلاق؟'))return;return call6('approve',{id,expectedStatus:r.status,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تمت الموافقة وإعادة الدفعة لصاحب الطلب')};
const close74=closeRequest;closeRequest=async function(id){const r=db.requests.find(r=>r.id===id);if(!r?.withoutEngineer74)return close74(id);if(closing74||cloudBusy)return;const block=executionBlockReason53(r);if(block)return appMessage(block,'warning');const file=selectedReportFile||document.getElementById('reportPhoto')?.files?.[0]||document.getElementById('cameraPhoto')?.files?.[0],method=document.getElementById('actualInjectionMethod')?.value,actualBatchQty=Number(document.getElementById('actualBatchQty')?.value||0),comments=document.getElementById('comments')?.value.trim(),actualItems=requestItems(r).map(i=>({...i,actualQty:Number(document.getElementById('actual-'+i.productId)?.value)}));if(!file||!signatureHasInk||!signatureCanvas||!comments||!['manual','machines'].includes(method)||!Number.isSafeInteger(actualBatchQty)||actualBatchQty<=0||actualItems.some(i=>!Number.isSafeInteger(i.actualQty)||i.actualQty<0)||!actualItems.some(i=>i.actualQty>0))return appMessage('أكمل الفعلي والطيور والتقرير والإمضاء والملاحظات.','warning');closing74=true;try{const payload={id,expectedStatus:r.status,injectionMethod:method,actualBatchQty,comments,actualItems,reportPhoto:file.name,reportPhotoData:await fileToImageData(file),signatureData:signatureCanvas.toDataURL('image/png')};const signature=JSON.stringify([session.authUserId,payload]);if(closeRetry74?.signature!==signature)closeRetry74={signature,operationId:crypto.randomUUID()};if(await call6('close',{...payload,operationId:closeRetry74.operationId,expectedRevision:cloudRevision},'تم إغلاق واعتماد الدفعة وخصم الاستهلاك الفعلي')){closeRetry74=null;tab='home';render()}}catch(e){appMessage(e.message||'تعذر حفظ التقرير','error')}finally{closing74=false}};
const progress74=requestProgress;requestProgress=function(r){if(!r.withoutEngineer74)return progress74(r);const phases=[['registered','تم تسجيل الطلب',ICONS73.registered],['approval','بانتظار الموافقة','◷'],['distributed','تمت الموافقة',ICONS73.distributed],['acknowledged','تم الإغلاق والاعتماد',ICONS73.acknowledged]],current=r.status==='done'?3:r.status==='approved'?2:1;return `<div class="without74">دفعة بدون مهندس</div><div class="phases73 no-engineer74">${phases.map(([key,label,icon],i)=>`<span class="phase73 ${key} ${i<=current?'passed':'future'} ${i===current?'current':''}"><i>${i<current?'✓':icon}</i><b>${label}</b></span>`).join('')}</div>${['rejected','cancelled','postponed'].includes(r.status)?`<div class="action73 ${status73(r)}">${statusLabel73(r)}</div>`:''}`};
const label74=statusLabel73,statusKey74=status73;statusLabel73=function(r){return r.withoutEngineer74&&r.status==='approved'?'تمت الموافقة — بانتظار تقرير صاحب الطلب':label74(r)};status73=function(r){return r.withoutEngineer74&&r.status==='approved'?'distributed':statusKey74(r)};
const review74=reviewReport71;reviewReport71=async function(id,approve){const r=db.requests.find(r=>r.id===id);if(source74(r?.source)!=='رصيد المعمل نفسه'||!approve)return review74(id,approve);if(cloudBusy||!canAck73(r)||!await appConfirm('اعتماد تقرير رصيد المعمل نفسه وإغلاق الدفعة دون خصم من أي رصيد؟'))return;return call6('report_ack71',{id,reason:'اعتماد التنفيذ من رصيد المعمل نفسه دون خصم مالي',expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تم اعتماد التنفيذ والإغلاق دون خصم من الأرصدة')};
const mail74=mailDraft73;mailDraft73=function(r){const draft=mail74(r);if(r.withoutEngineer74||source74(r.source)==='رصيد المعمل نفسه'){const cfg=db.mailRouting73||{},sayed=cfg.sayed||(db.mailContacts73||[]).find(c=>c.employeeId==='EMP-015')?.email||'',ashraf=cfg.ashraf||'ashraf.mostafa@ift-online.com',walid=cfg.walid||(db.mailContacts73||[]).find(c=>c.employeeId==='EMP-017')?.email||'',manager=cfg['manager:'+r.region]||'';draft.to=r.withoutEngineer74?sayed:ashraf;draft.cc=[r.withoutEngineer74?ashraf:sayed,walid,manager].filter((e,i,a)=>e&&e!==draft.to&&a.indexOf(e)===i);draft.subject=`${r.withoutEngineer74?'Approval Required — Batch Without Engineer':'Injection Distribution Request'} | ${r.id} | ${r.customerName}`;draft.body=[r.withoutEngineer74?'مطلوب موافقة دكتور سيد على دفعة بدون مهندس. يعود الطلب لصاحبه لرفع التقرير والإغلاق.':'طلب حقن من رصيد المعمل نفسه. يسجل التنفيذ فقط دون أي خصم مالي.',`الطلب: ${r.id}`,`العميل: ${r.customerName}`,`المزرعة: ${r.farmName}`,`المعمل: ${r.lab}`,`المنطقة: ${r.region}`,`المصدر: ${source74(r.source)}`,`الموعد: ${r.batchAt}`,`عدد الطيور: ${r.batchQty}`,...requestItems(r).map(i=>`${i.productName}: ${i.requestedQty}`),'التقرير والاعتماد داخل FortiMune.'].join('\n')}return draft};
// Performance uses completed physical work, including lab-owned stock. Finance remains ledger-only.
let performance74={engineer:'ALL',source:'ALL'};
const engineerKey74=r=>r.withoutEngineer74?'REQUESTER':r.engineerEmployeeId||r.engineerId||r.engineerName||'UNASSIGNED';
function ampoules74(r){return (r.actualItems||[]).filter(i=>!dash61.product||dash61.product==='ALL'||i.productId===dash61.product).reduce((n,i)=>n+Number(i.actualQty||0),0)}
function metrics74(rows){return [new Set(rows.map(r=>r.customerId)).size,rows.length,rows.reduce((n,r)=>n+Number(r.actualBatchQty||r.actualBatchCount||0),0),rows.reduce((n,r)=>n+ampoules74(r),0)]}
function performanceRows74(){const d=dashData61();return d.done.filter(r=>(performance74.source==='ALL'||source74(r.source)===performance74.source)&&(performance74.engineer==='ALL'||engineerKey74(r)===performance74.engineer)&&(!dash61.product||dash61.product==='ALL'||(r.actualItems||[]).some(i=>i.productId===dash61.product&&Number(i.actualQty)>0))).sort((a,b)=>String(a.closedAt).localeCompare(String(b.closedAt)))}
function performanceGroups74(rows,daily=false){const groups=new Map();for(const r of rows){const key=(daily?dailyDateOnly(r.closedAt)+'|':'')+engineerKey74(r);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}return [...groups.values()].map(rs=>[...(daily?[dailyDateOnly(rs[0].closedAt)]:[]),rs[0].withoutEngineer74?'بدون مهندس — '+(rs[0].createdBy||rs[0].closedBy||'صاحب الطلب'):rs[0].engineerName||'غير مسجل',...metrics74(rs)])}
function setPerformance74(key,value){performance74[key]=value;render()}
function filters74(){const all=dashData61().done,engineers=[...new Map(all.filter(r=>!r.withoutEngineer74).map(r=>[engineerKey74(r),r.engineerName||'غير مسجل'])).entries()];return `<section class="card request-form-grid"><div><label>مصدر الأمبولات</label><select onchange="setPerformance74('source',this.value)">${[['ALL','كل المصادر'],...SOURCES74.map(s=>[s,s])].map(([id,n])=>`<option value="${esc(id)}" ${performance74.source===id?'selected':''}>${esc(n)}</option>`).join('')}</select></div>${session.role!=='engineer'?`<div><label>المهندس / مسار التنفيذ</label><select onchange="setPerformance74('engineer',this.value)">${[['ALL','كل المهندسين والمسارات'],...engineers,['REQUESTER','بدون مهندس']].map(([id,n])=>`<option value="${esc(id)}" ${performance74.engineer===id?'selected':''}>${esc(n)}</option>`).join('')}</select></div>`:''}</section>`}
function batchCards74(rows){return rows.map(r=>`<details class="card batch74 status-${status73(r)}" data-request-id="${esc(r.id)}"><summary><div><b>${esc(r.customerName)}</b><small>${fmtBatchDate(r.batchAt)} • ${esc(r.id)}</small></div><span class="arrow67"></span></summary><div class="disclosure-body67"><div class="facts74"><div><small>المزرعة</small><b>${esc(r.farmName||'—')}</b></div><div><small>المعمل</small><b>${esc(r.lab||'—')}</b></div><div><small>المنطقة</small><b>${esc(r.region||'—')}</b></div><div><small>تاريخ التنفيذ</small><b>${r.closedAt?fmtDate(r.closedAt):'لم ينفذ بعد'}</b></div><div><small>مصدر الأمبولات</small><b>${esc(source74(r.source))}</b></div><div><small>التنفيذ</small><b>${esc(r.withoutEngineer74?'بدون مهندس — '+(r.closedBy||r.createdBy||'صاحب الطلب'):r.engineerName||'—')}</b></div><div><small>الطيور الفعلية</small><b>${Number(r.actualBatchQty||0).toLocaleString()}</b></div><div><small>الأمبولات الفعلية</small><b>${ampoules74(r)}</b></div></div>${requestProgress(r)}${table69(['الصنف','المطلوب','الاستهلاك الفعلي'],requestItems(r).map(i=>[i.productName,i.requestedQty,(r.actualItems||[]).find(a=>a.productId===i.productId)?.actualQty??'—']))}<div class="actions">${actionFor(r,session.role==='engineer'?'jobs':session.role==='injection_manager'?'inbox':'')}${ackButtons71(r)}</div></div></details>`).join('')||'<p class="card">لا توجد دفعات خلال الفترة والفلاتر المختارة.</p>'}
const dashboard74=VIEWS.dashboard61;VIEWS.dashboard61=function(){if(!validRange5(dash61))return title5('','لوحة المؤشرات')+dashFilters61()+'<p class="alert danger">راجع الفترة.</p>';const d=dashData61(),rows=performanceRows74();if(!d.engineering){const root=document.createElement('div');root.innerHTML=dashboard74();const all=root.querySelector('#dashBatches67');if(all)all.outerHTML=`<section><h3>تفاصيل دفعات الفترة</h3>${batchCards74(d.rows)}</section>`;return root.innerHTML}const metrics=metrics74(rows),cards=[['العملاء',metrics[0],'blue'],['الدفعات المكتملة',metrics[1],'green'],['الطيور المحصنة',metrics[2],'purple'],['الأمبولات المستهلكة',metrics[3],'injected']];return title5('','لوحة أداء الحقن',session.role==='engineer'?'أداؤك خلال الفترة المختارة':'أداء المهندسين والتنفيذ اليومي خلال الفترة المختارة')+dashFilters61()+filters74()+`<div class="v5-report-bar"><button class="green" onclick="exportDash61()">تصدير Excel ↓</button></div><div class="v5-stats performance-stats74">${cards.map(([label,n,color])=>`<div class="v5-stat ${color}"><span>${label}</span><strong>${Number(n).toLocaleString()}</strong></div>`).join('')}</div><section class="card"><h3>${session.role==='engineer'?'ملخص أدائك':'أداء المهندسين'}</h3>${performanceCards74(rows)}</section><section class="card"><h3>الأداء اليومي</h3>${performanceCards74(rows,true)}</section><section><h3>الدفعات المكتملة (${rows.length})</h3>${batchCards74(rows)}</section>`};
const exportDashboard74=exportDash61;exportDash61=function(){if(!engineering71())return exportDashboard74();if(!validRange5(dash61))return;const rows=performanceRows74();downloadExcel5('FortiMune-Engineer-Performance',[{name:'أداء المهندسين',rows:[['المهندس / المنفذ','العملاء','الدفعات','الطيور','الأمبولات'],...performanceGroups74(rows)]},{name:'الأداء اليومي',rows:[['التاريخ','المهندس / المنفذ','العملاء','الدفعات','الطيور','الأمبولات'],...performanceGroups74(rows,true)]},{name:'تفاصيل الدفعات',rows:[['تاريخ التنفيذ','الطلب','العميل','المزرعة','المنطقة','المصدر','المهندس / المنفذ','حضور المهندس','الطيور',...PRODUCTS.map(p=>p.name)],...rows.map(r=>[dailyDateOnly(r.closedAt),r.id,r.customerName,r.farmName,r.region,source74(r.source),r.withoutEngineer74?r.closedBy:r.engineerName,attendance74(r),r.actualBatchQty,...PRODUCTS.map(p=>(!dash61.product||dash61.product==='ALL'||p.id===dash61.product)?(r.actualItems||[]).filter(i=>i.productId===p.id).reduce((n,i)=>n+Number(i.actualQty||0),0):'')])]},{name:'الفلاتر',rows:[['من',dash61.from],['إلى',dash61.to],['العميل',dash61.customer],['المنطقة',dash61.region],['الصنف',dash61.product||'ALL'],['المهندس',performance74.engineer],['المصدر',performance74.source]]}])};
const expense74=VIEWS.expenses69;VIEWS.expenses69=function(){if(!isSayed6())return '<p class="card">مصاريف الحقن لدكتور سيد فقط.</p>';const root=document.createElement('div');root.innerHTML=expense74();const rows=injectionRows5();const table=root.querySelector('.v5-table table');if(table){table.querySelector('thead tr')?.insertAdjacentHTML('beforeend','<th>حضور المهندس</th>');table.querySelectorAll('tbody tr').forEach((tr,i)=>{if(rows[i])tr.insertAdjacentHTML('beforeend',`<td>${attendance74(rows[i])}</td>`)})}return root.innerHTML};
const exportExpense74=exportExpenses69;exportExpenses69=function(){if(!isSayed6())return;const old=downloadExcel5;downloadExcel5=function(name,sheets){const records=injectionRows5();if(sheets[0]?.rows?.length){sheets[0].rows[0].push('حضور المهندس');sheets[0].rows.slice(1).forEach((row,i)=>row.push(records[i]?attendance74(records[i]):''))}return old(name,sheets)};try{return exportExpense74()}finally{downloadExcel5=old}};
const openReport74=openClose;openClose=function(id){openReport74(id);const r=db.requests.find(r=>r.id===id);if(!r?.withoutEngineer74||executionBlockReason53(r))return;const status=document.querySelector('.execution-status');if(status)status.textContent='✓ تمت الموافقة — بدون مهندس';const assigned=document.querySelector('.execution-card-head .badge');if(assigned)assigned.textContent='صاحب الطلب';const title=document.querySelector('.execution-hero h1');if(title)title.textContent='رفع التقرير وإغلاق الدفعة بدون مهندس';const btn=document.getElementById('closeSubmitBtn');if(btn)btn.textContent='إغلاق واعتماد التنفيذ وخصم الفعلي'};
const tabs74=tabsForRole;tabsForRole=function(){return [...tabs74(),...(customerCreate66()?[['newRequestWithout74','طلب دفعة بدون مهندس']]:[]),...(canViewAggregateReports()?[['labAnalytics74','استهلاك المعامل']]:[])]};navGroup.labAnalytics74='reports';
const inbox74=VIEWS.inbox;VIEWS.inbox=function(){return title5('','طلبات الحقن الواردة')+requestTable(accessibleRequests().filter(r=>!r.withoutEngineer74&&['pending','approved','postponed','not_executed'].includes(r.status)),'inbox')};
const filtersPrevious74=filters74;filters74=function(){const h=filtersPrevious74(),scope=scopedRequests61(),regions=[...new Set(scope.map(r=>r.region))],customers=[...new Map(scope.map(r=>[r.customerId,r.customerName])).entries()];return h+`<section class="card request-form-grid"><div><label>المنطقة</label><select onchange="dashSet61('region',this.value)">${[['ALL','كل المناطق المتاحة'],...regions.map(x=>[x,x])].map(([id,n])=>`<option value="${esc(id)}" ${dash61.region===id?'selected':''}>${esc(n)}</option>`).join('')}</select></div><div><label>العميل</label><select onchange="dashSet61('customer',this.value)">${[['ALL','كل العملاء المتاحين'],...customers].map(([id,n])=>`<option value="${esc(id)}" ${dash61.customer===id?'selected':''}>${esc(n)}</option>`).join('')}</select></div></section>`};
// Export this date-based expense report directly; attendance stays aligned with each row.
exportExpenses69=function(){if(!isSayed6()||!validRange5(injectionFilter))return;const rows=injectionRows5();downloadExcel5('FortiMune-Injection-Expenses',[{name:'مصاريف الحقن',rows:[['تاريخ التنفيذ','الطلب','العميل','المزرعة','المعمل','المنطقة','مصدر الأمبولات','المهندس / المنفذ','حضور المهندس','الطيور',...PRODUCTS.map(p=>p.name)],...rows.map(r=>[dailyDateOnly(r.closedAt),r.id,r.customerName,r.farmName,r.lab,r.region,source74(r.source),r.withoutEngineer74?r.closedBy:r.engineerName,attendance74(r),r.actualBatchQty,...PRODUCTS.map(p=>(r.actualItems||[]).filter(i=>i.productId===p.id).reduce((n,i)=>n+Number(i.actualQty||0),0))])]},{name:'ملخص الفترة',rows:[['البند','الإجمالي'],['العملاء',new Set(rows.map(r=>r.customerId)).size],['الدفعات',rows.length],['الطيور',rows.reduce((n,r)=>n+Number(r.actualBatchQty||0),0)],...PRODUCTS.filter(p=>injectionFilter.product==='ALL'||p.id===injectionFilter.product).map(p=>[p.name,rows.reduce((n,r)=>n+(r.actualItems||[]).filter(i=>i.productId===p.id).reduce((a,i)=>a+Number(i.actualQty||0),0),0)])]},{name:'الفلاتر',rows:Object.entries(injectionFilter)}])};
let labFilter74={from:'',to:'',region:'ALL',customer:'ALL',source:'ALL',product:'ALL'},labOwner74='';
function labRows74(){if(labOwner74!==session?.authUserId){labOwner74=session?.authUserId;labFilter74={from:'',to:'',region:'ALL',customer:'ALL',source:'ALL',product:'ALL'}}return accessibleRequests().filter(r=>{const f=labFilter74,day=dailyDateOnly(r.closedAt),source=source74(r.source);return r.status==='done'&&['رصيد العميل في المعمل','رصيد المعمل نفسه'].includes(source)&&(!f.from||day>=f.from)&&(!f.to||day<=f.to)&&(f.region==='ALL'||r.region===f.region)&&(f.customer==='ALL'||r.customerId===f.customer)&&(f.source==='ALL'||source===f.source)&&(f.product==='ALL'||(r.actualItems||[]).some(i=>i.productId===f.product&&Number(i.actualQty)>0))}).sort((a,b)=>String(a.closedAt).localeCompare(String(b.closedAt)))}
function labSummary74(){const groups=new Map();for(const r of labRows74())for(const i of r.actualItems||[]){if(labFilter74.product!=='ALL'&&i.productId!==labFilter74.product)continue;const key=JSON.stringify([r.region,r.customerId,r.lab,source74(r.source),i.productId]);if(!groups.has(key))groups.set(key,[r.region,r.customerName,r.lab,source74(r.source),i.productName||PRODUCTS.find(p=>p.id===i.productId)?.name,0]);groups.get(key)[5]+=Number(i.actualQty||0)}return [...groups.values()]}
function setLabFilter74(key,value){labFilter74[key]=value;render()}
VIEWS.labAnalytics74=function(){if(!canViewAggregateReports())return '';const rows=labRows74(),scope=accessibleRequests(),regions=[...new Set(scope.map(r=>r.region))],customers=[...new Map(scope.map(r=>[r.customerId,r.customerName])).entries()],select=(key,label,options)=>`<div><label>${label}</label><select onchange="setLabFilter74('${key}',this.value)">${[['ALL','الكل'],...options].map(([id,n])=>`<option value="${esc(id)}" ${labFilter74[key]===id?'selected':''}>${esc(n)}</option>`).join('')}</select></div>`;return title5('','استهلاك المعامل','الحقن الفعلي حسب المنطقة والمعمل والصنف؛ رصيد المعمل نفسه دون أثر مالي')+`<section class="card request-form-grid"><div class="date-range54"><div><label>من</label><input type="date" value="${labFilter74.from}" onchange="setLabFilter74('from',this.value)"></div><div><label>إلى</label><input type="date" value="${labFilter74.to}" onchange="setLabFilter74('to',this.value)"></div></div>${select('region','المنطقة',regions.map(r=>[r,r]))}${select('customer','العميل / المعمل',customers)}${select('source','المصدر',['رصيد العميل في المعمل','رصيد المعمل نفسه'].map(s=>[s,s]))}${select('product','الصنف',PRODUCTS.map(p=>[p.id,p.name]))}</section><div class="actions"><button class="green" onclick="exportLab74()">تصدير Excel ↓</button><span>${rows.length} دفعة • ${new Set(rows.map(r=>r.customerId)).size} عميل / معمل</span></div>${labFilter74.from&&labFilter74.to&&labFilter74.from>labFilter74.to?'<p class="alert danger">راجع الفترة المختارة.</p>':table69(['المنطقة','العميل / المعمل','المعمل','المصدر','الصنف','الأمبولات المستهلكة'],labSummary74())}<p class="muted">البيانات تدعم تحليل الاستهلاك. حساب Market Share الكامل يحتاج إجمالي السوق أو استهلاك المنافسين.</p>${batchCards74(rows)}`};
function exportLab74(){if(!canViewAggregateReports()||!validRange5(labFilter74))return;downloadExcel5('FortiMune-Lab-Consumption',[{name:'استهلاك المعامل',rows:[['المنطقة','العميل / المعمل','المعمل','المصدر','الصنف','الأمبولات المستهلكة'],...labSummary74()]},{name:'تفاصيل التنفيذ',rows:[['التاريخ','الطلب','العميل','المعمل','المزرعة','المنطقة','المصدر','المنفذ','حضور المهندس','الطيور','الصنف','الفعلي'],...labRows74().flatMap(r=>(r.actualItems||[]).filter(i=>labFilter74.product==='ALL'||i.productId===labFilter74.product).map(i=>[dailyDateOnly(r.closedAt),r.id,r.customerName,r.lab,r.farmName,r.region,source74(r.source),r.withoutEngineer74?r.closedBy:r.engineerName,attendance74(r),r.actualBatchQty,i.productName,i.actualQty]))]},{name:'الفلاتر',rows:Object.entries(labFilter74)}])}
const reportMenu74=VIEWS.reports;VIEWS.reports=function(){return reportMenu74()+(canViewAggregateReports()?tile5('▥','استهلاك المعامل','تحليل استهلاك الأمبولات حسب المنطقة والمعمل والصنف','labAnalytics74','blue'):'')};

function performanceCards74(rows,daily=false){return performanceGroups74(rows,daily).map(row=>{const offset=daily?1:0,name=row[offset],values=row.slice(offset+1),body=`<div class="performance-metrics74">${['العملاء','الدفعات','الطيور','الأمبولات'].map((label,i)=>`<div><small>${label}</small><b>${Number(values[i]).toLocaleString()}</b></div>`).join('')}</div>`;return daily?`<details class="daily-performance74"><summary><b>${esc(name)}</b><span>${fmtBatchDate(row[0])}</span><span class="arrow67"></span></summary>${body}</details>`:`<article class="engineer-performance74"><h4>${esc(name)}</h4>${body}</article>`}).join('')||'<p class="muted">لا يوجد تنفيذ خلال الفترة والفلاتر المختارة.</p>'}

let performanceOwner74='';const rowsPrevious74=performanceRows74;performanceRows74=function(){if(performanceOwner74!==session?.authUserId){performanceOwner74=session?.authUserId;performance74={engineer:'ALL',source:'ALL'}}return rowsPrevious74()};
const monthlyPrevious74=monthlyReport70;monthlyReport70=function(){const root=document.createElement('div');root.innerHTML=monthlyPrevious74();root.querySelectorAll('details.day-report70').forEach(day=>{const section=document.createElement('section');section.className='day-section74';const summary=day.querySelector(':scope > summary');section.innerHTML=`<h3>${summary?.textContent||''}</h3>`;const body=day.querySelector(':scope > .disclosure-body67');if(body)while(body.firstChild)section.appendChild(body.firstChild);day.replaceWith(section)});return root.innerHTML};VIEWS.daily=monthlyReport70;injection5=monthlyReport70;
