/* 7.2: client acknowledgement and team replenishment are independent. */
const pendingReport72=r=>r.status==='done'&&r.reportAcknowledgement71==='pending'&&!r.balanceDeductedAt;
ackButtons71=function(r){if(!pendingReport72(r))return '';return `<div class="alert warning">بانتظار اعتماد التنفيذ؛ لم يُخصم الاستهلاك من العميل.</div>${r.createdByEmployeeId===session.employeeId&&!engineering71()?`<div class="actions"><button class="green save6" onclick="reviewReport71(${attr66(r.id)},true)">✓ اعتماد التنفيذ</button><button class="orange save6" onclick="reviewReport71(${attr66(r.id)},false)">إرجاع التقرير للمراجعة</button></div>`:''}`};
VIEWS.reportApprovals71=function(){const rows=accessibleRequests().filter(r=>pendingReport72(r)&&(isTopManagementRole(session.role)||r.createdByEmployeeId===session.employeeId));return title5('','اعتماد التنفيذ','مراجعة التقرير لكل المصادر؛ الخصم بعد الاعتماد مرة واحدة')+rows.map(r=>`<details class="card disclosure67"><summary><span><b>${esc(r.customerName)} • ${esc(r.id)}</b><small>${fmtDate(r.closedAt)} • ${esc(r.source)}</small></span><span class="arrow67"></span></summary><div class="disclosure-body67">${reportFacts72(r)}<button class="open-request70" onclick="handleBatchLink68(${attr66(r.id)})">رؤية تقرير الدفعة</button>${ackButtons71(r)}</div></details>`).join('')+(rows.length?'':'<p class="card">لا توجد تقارير بانتظار الاعتماد.</p>')};
function reportFacts72(r){return `<div class="facts72">${[['العميل',r.customerName],['رقم الطلب',r.id],['اسم الدفعة',r.batchName||r.farmName],['المزرعة',r.farmName],['المنطقة',r.region],['مصدر الأمبولات',r.source],['فريق الحقن',r.injectionTeam],['المهندس',r.engineerName],['تاريخ الدفعة',fmtBatchDate(r.batchAt)],['تاريخ الحقن',fmtDate(r.closedAt)],['اعتماد التنفيذ',fmtDate(r.reportAcknowledgedAt71)]].map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v||'—')}</b></div>`).join('')}</div>`}
function coverage72(r,pid){const d=(db.deficits71||[]).find(d=>d.entityType==='customer'&&d.requestId===r.id&&d.productId===pid);const legacy=(db.customerSettlements70||[]).filter(x=>x.requestId===r.id).flatMap(x=>x.items||[]).filter(i=>i.productId===pid).reduce((n,i)=>n+Number(i.covered||0),0);return Number(r.coverage72?.[pid]??legacy)+Number(d?.qty||0)-Number(d?.remaining||0)}
function teamItems72(r){return (r.actualItems||[]).map(i=>{const actual=Number(i.actualQty||0),paid=Number(r.teamReplenished?.[i.productId]||0);return {...i,actual,paid,remaining:Math.max(0,actual-paid),available:Math.max(0,Math.min(actual,coverage72(r,i.productId))-paid)}})}
settlementBadge71=function(r){const rows=teamItems72(r),remaining=rows.reduce((n,i)=>n+i.remaining,0),paid=rows.reduce((n,i)=>n+i.paid,0);return `<span class="status70 ${remaining?paid?'partial70':'pending70':'complete70'}">${remaining?paid?'تسوية جزئية 🟠':'لم تتم التسوية ❗':'تمت التسوية بالكامل ✅'}</span>`};
batchDisclosure69=function(r,settlement=false){const rows=teamItems72(r);return `<details class="card disclosure67" data-request-id="${esc(r.id)}"><summary><span><b>${esc(r.customerName)} • ${esc(r.id)}</b><small>${fmtDate(r.closedAt)} • ${esc(r.injectionTeam)}</small>${settlementBadge71(r)}</span><span class="arrow67"></span></summary><div class="disclosure-body67">${reportFacts72(r)}${table69(['الصنف','الفعلي','تمت تسويته','المتاح للتسوية','المتبقي'],rows.map(i=>[i.productName||PRODUCTS.find(p=>p.id===i.productId)?.name,i.actual,i.paid,i.available,i.remaining]))}<div class="actions"><button class="open-request70" onclick="handleBatchLink68(${attr66(r.id)})">رؤية تقرير الدفعة</button>${settlement&&r.balanceDeductedAt&&rows.some(i=>i.available>0)?`<button class="green save6" onclick="settleBatch71(${attr66(r.id)})">${rows.every(i=>i.available>=i.remaining)?'تسوية كلية':'تسوية جزئية'}</button>`:settlement&&rows.some(i=>i.remaining)?'<p class="alert warning">لا يسمح بإتمام التسوية لعدم وجود رصيد يغطي الكمية.</p>':''}${settlement&&rows.some(i=>i.paid>0)?`<button class="ghost" onclick="editSettlement72(${attr66(r.id)})">تعديل التسوية</button>`:''}</div><h4>سجل التسويات والتعديلات</h4>${table69(['التاريخ','الصنف','قبل','بعد','السبب','بواسطة'],(db.teamSettlements72||[]).filter(x=>x.requestId===r.id).flatMap(x=>(x.items||[]).map(i=>[fmtDate(x.createdAt),PRODUCTS.find(p=>p.id===i.productId)?.name,i.before,i.after,x.reason,x.by])))}</div></details>`};
settleBatch71=async function(id){if(!isSayed6()||cloudBusy)return;const reason=prompt('سبب تسوية الفريق','تعويض الأمبولات المستهلكة للدفعة')||'';if(reason.trim().length<3)return;if(!await appConfirm('إضافة الكمية المغطّاة للفريق فقط، دون تغيير رصيد العميل؟'))return;return call6('team_settle72',{id,reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تم حفظ تسوية فريق الحقن بنجاح')};
function editSettlement72(id){const r=db.requests.find(r=>r.id===id);if(!isSayed6()||!r)return;const el=document.createElement('div');el.id='settlementEdit72';el.className='app-confirm-overlay';el.innerHTML=`<section class="app-confirm"><h3>تعديل التسوية</h3>${teamItems72(r).map(i=>`<label>${esc(i.productName||i.productId)} — إجمالي الكمية المعوّضة</label><input data-product72="${esc(i.productId)}" type="number" min="0" max="${i.actual}" step="1" value="${i.paid}">`).join('')}<label>سبب التعديل</label><textarea id="editReason72"></textarea><div class="actions"><button class="green save6" onclick="submitSettlementEdit72(${attr66(id)})">حفظ التعديل</button><button class="ghost" onclick="document.getElementById('settlementEdit72').remove()">إلغاء</button></div></section>`;document.getElementById(el.id)?.remove();document.body.append(el)}
async function submitSettlementEdit72(id){const quantities=Object.fromEntries([...document.querySelectorAll('[data-product72]')].map(el=>[el.dataset.product72,Number(el.value)])),reason=document.getElementById('editReason72').value.trim();if(reason.length<3||Object.values(quantities).some(n=>!Number.isSafeInteger(n)||n<0))return appMessage('راجع الكميات واكتب السبب','warning');if(await call6('team_settlement_edit72',{id,quantities,reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},'تم تعديل التسوية وتحديث العجز'))document.getElementById('settlementEdit72')?.remove()}
VIEWS.teamSettlement69=function(){if(!isSayed6())return '';return title5('','تسوية فرق الحقن',`تاريخ اليوم: ${fmtBatchDate(cairoDate66(new Date().toISOString()))}`)+filters69()+batches69().filter(r=>r.balanceDeductedAt).map(r=>batchDisclosure69(r,true)).join('')+`<button class="green" onclick="exportSettlement72()">تصدير التسوية Excel</button>`};
openTransfer6=function(){go('teamSettlement69')};
function exportSettlement72(){downloadExcel5('FortiMune-Team-Settlement',[{name:'التسوية',rows:[['الطلب','العميل','الفريق','التاريخ','الصنف','الفعلي','تمت تسويته','المتبقي'],...batches69().filter(r=>r.balanceDeductedAt).flatMap(r=>teamItems72(r).map(i=>[r.id,r.customerName,r.injectionTeam,r.closedAt,i.productName,i.actual,i.paid,i.remaining]))]}])}
const deficitPageOld72=deficitPage71;
deficitPage71=function(kind){const rows=deficitRows71(kind),groups=new Map();for(const d of rows){const key=d.requestId||d.id;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(d)}const root=document.createElement('div');root.innerHTML=deficitPageOld72(kind);root.querySelectorAll('details.card.disclosure67').forEach(el=>el.remove());const count=[...root.querySelectorAll('p')].find(el=>/^\d+ سجل$/.test(el.textContent));if(count)count.textContent=groups.size+' دفعة / سجل';for(const [key,items] of groups){const first=items[0],r=db.requests.find(x=>x.id===first.requestId),c=db.customers.find(x=>x.id===first.customerId);root.insertAdjacentHTML('beforeend',`<details class="card disclosure67 deficit72"><summary><span><b>${esc(c?.name||first.customerName||first.team)} • ${esc(key)}</b><small>${fmtBatchDate(dailyDateOnly(first.injectionDate||first.createdAt))}</small><div class="deficit-chips72">${items.map(d=>`<span class="${d.remaining>0?'negative6':'status70 complete70'}">${esc(PRODUCTS.find(p=>p.id===d.productId)?.name)}: <b dir="ltr">${d.remaining>0?'−'+d.remaining:'0 ✓'}</b> ${d.remaining>0?'❗':''}</span>`).join('')}</div></span><span class="arrow67"></span></summary><div class="disclosure-body67">${r?reportFacts72(r):`<p>${esc(first.reason)}</p>`}${table69(['الصنف','العجز الأصلي','تمت تغطيته','العجز الحالي'],items.map(d=>[PRODUCTS.find(p=>p.id===d.productId)?.name,d.qty,d.qty-d.remaining,'−'+d.remaining]))}${r?`<button class="open-request70" onclick="handleBatchLink68(${attr66(r.id)})">رؤية تقرير الدفعة</button>`:''}${isSayed6()?items.filter(d=>d.remaining>0).map(d=>`<button class="ghost" onclick="adjustDeficit71(${attr66(d.id)})">تغطية ${esc(PRODUCTS.find(p=>p.id===d.productId)?.name)} بتعديل افتتاحي</button>`).join(''):''}<h4>سجل التغطية والتسويات</h4>${table69(['الصنف','التاريخ','الكمية','السبب','المستند','بواسطة'],items.flatMap(d=>(d.history||[]).map(h=>[PRODUCTS.find(p=>p.id===d.productId)?.name,fmtDate(h.date),h.qty,h.reason,h.reference,h.by])))}</div></details>`)}return root.innerHTML};
const menuOld72=VIEWS.menu61;VIEWS.menu61=function(){const root=document.createElement('div');root.innerHTML=menuOld72();const grid=root.querySelector('.menu-grid62');root.querySelectorAll('[onclick]').forEach(el=>{const id=el.getAttribute('onclick')?.match(/(?:go|menuGo61)\('([^']+)'\)/)?.[1];if(id==='daily'||['customerChanges70','customerChange70'].includes(id)&&engineering71())el.remove()});if(grid){for(const id of ['customers','deficits71','reports']){const entry=[...root.querySelectorAll('.menu-entry62')].find(el=>new RegExp("\\('"+id+"'\\)").test(el.getAttribute('onclick')||''));if(entry)grid.prepend(entry)}}return root.innerHTML};
const requestsOld72=VIEWS.requests66;VIEWS.requests66=function(){const h=requestsOld72().replace('مراجعة تقارير الشركة والمعمل قبل خصم الاستهلاك','مراجعة التنفيذ لكل المصادر قبل خصم الاستهلاك');return financial71()?h+tile5('✓','موافقات البيع والمرتجعات','طلبات تنتظر قرار دكتور سيد','financeRequests72','orange'):h};
const tabsOld72=tabsForRole;tabsForRole=function(){return [...tabsOld72(),...(financial71()?[['financeRequests72','موافقات البيع والمرتجعات']]:[])]};navGroup.financeRequests72='requests66';
VIEWS.financeRequests72=function(){if(!financial71())return '';return title5('','طلبات البيع والمرتجعات')+(db.financeRequests72||[]).slice().sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))).map(r=>`<details class="card disclosure67"><summary><span><b>${esc(r.customerName)} — ${r.kind==='invoice'?'فاتورة بيع':'مرتجع'}</b><small>${fmtDate(r.createdAt)} • ${esc(r.createdBy)}</small><span class="status70 ${r.status==='pending'?'partial70':r.status==='approved'?'complete70':'pending70'}">${r.status==='pending'?'بانتظار الموافقة':r.status==='approved'?'تمت الموافقة':'مرفوض'}</span></span><span class="arrow67"></span></summary><div class="disclosure-body67">${table69(['الصنف','الكمية'],(r.payload?.items||[]).map(i=>[i.productName||i.productId,i.qty]))}<p>${esc(r.reason||'')}</p>${isSayed6()&&r.status==='pending'?`<button class="green save6" onclick="reviewFinance72(${attr66(r.id)},true)">موافقة وتنفيذ</button><button class="red save6" onclick="reviewFinance72(${attr66(r.id)},false)">رفض</button>`:''}</div></details>`).join('')};
async function reviewFinance72(id,approve){const reason=approve?'تمت مراجعة الطلب والموافقة':prompt('سبب الرفض')||'';if(reason.length<3||!await appConfirm(approve?'تنفيذ الحركة المالية مرة واحدة؟':'رفض الطلب؟'))return;return call6(approve?'finance_approve72':'finance_reject72',{id,reason,expectedRevision:cloudRevision,operationId:crypto.randomUUID()},approve?'تمت الموافقة وتنفيذ العملية':'تم رفض الطلب',approve?'success':'warning')}
async function saveFinance72(kind){if(!financial71()||cloudBusy)return;const ret=kind==='return',prefix=ret?'ret':'inv',customerId=document.getElementById(ret?'returnCustomer':'invoiceCustomer')?.value,date=document.getElementById(ret?'returnDate':'invoiceDate')?.value,items=PRODUCTS.map(p=>({productId:p.id,productName:p.name,qty:Number(document.getElementById(prefix+'-'+p.id)?.value||0)})).filter(i=>i.qty!==0);if(!customerId||!date||!items.length||items.some(i=>!Number.isSafeInteger(i.qty)||i.qty<=0))return appMessage('راجع العميل والتاريخ والكميات','warning');const signature=JSON.stringify([customerId,date,items]);if(financialPending5[kind]?.signature!==signature)financialPending5[kind]={signature,id:(ret?'RET-':'INV-')+crypto.randomUUID(),operationId:crypto.randomUUID()};const token=financialPending5[kind];if(await call6(kind,{id:token.id,customerId,date,items,operationId:token.operationId,expectedRevision:cloudRevision},'تم إرسال الطلب، بانتظار موافقة دكتور سيد','warning')){delete financialPending5[kind];go('financeRequests72')}}
saveInvoice=()=>saveFinance72('invoice');saveReturn=()=>saveFinance72('return');
const invoiceView72=VIEWS.invoices,returnView72=VIEWS.returns;for(const [name,previous] of [['invoices',invoiceView72],['returns',returnView72]])VIEWS[name]=()=>previous().replace('حفظ الفاتورة وإضافة الرصيد','إرسال للموافقة').replace('حفظ المرتجع وخصم الرصيد','إرسال للموافقة').replace('رقم العملية تلقائي؛ الكميات تضاف إلى رصيد العميل','تضاف الكميات بعد موافقة دكتور سيد فقط');
// Financial reports use committed debits only; deferred actuals never become second consumption rows.
const movementOld72=movementRows;movementRows=function(){const original=db.movements;try{db.movements=original.filter(m=>Number(m.change)!==0);return movementOld72().filter(r=>!r.pendingAccounting71).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.details?.[0]?.date||'').localeCompare(String(b.details?.[0]?.date||'')))}finally{db.movements=original}};
const movementView72=VIEWS.movement;VIEWS.movement=()=>movementView72().replace(/<p class="alert">صفوف «فعلي، بانتظار المحاسبة»[\s\S]*?<\/p>/,'');
const dashOld72=dashData61;dashData61=function(){const d=dashOld72(),seen=new Set();d.movements=d.movements.filter(m=>{if(m.type!=='consumption')return true;const r=db.requests.find(r=>r.id===m.id)||db.requests.find(r=>(m.details||[]).some(x=>x.requestId===r.id));const key=r?.id||m.id;if(seen.has(key))return false;seen.add(key);return true});return d};
const detailedOld72=teamDetailed66;teamDetailed66=function(){return detailedOld72().sort((a,b)=>ledgerDate66(a).localeCompare(ledgerDate66(b))||String(a.date).localeCompare(String(b.date)))};
function teamCategory72(m){return /opening/.test(m.kind||'')?'adjustment':Number(m.change)<0&&!/settlement.*edit/.test(m.kind||'')?'consumption':'addition'}
teamKind66=function(m){return /opening/.test(m.kind||'')?'تعديل افتتاحي':m.kind==='team_settlement72'||m.isSettlement66||Number(m.change)>0?'إضافة / تسوية':'استهلاك / حقن'};
let teamTypes72=new Set(['opening','adjustment','addition','consumption','closing']);
function toggleTeamType72(type){teamTypes72.has(type)?teamTypes72.delete(type):teamTypes72.add(type);render()}
function teamSummaryRows72(){return teamSummary66().map(s=>[s.team,s.product,s.opening,s.openingChange,s.additions+s.settlements,s.debits,s.closing])}
function teamStatement72(){const rows=teamDetailed66().filter(m=>teamTypes72.has(teamCategory72(m))),s=teamSummary66();const headings=['تاريخ الأثر','وقت التسجيل','الفريق','الصنف','نوع الحركة','إضافة / خصم','الرصيد بعد الحركة','الدفعة','العميل','المسؤول','السبب'];const values=rows.map(m=>[ledgerDate66(m),fmtDate(m.date),m.team,PRODUCTS.find(p=>p.id===m.productId)?.name,teamKind66(m),m.change,m.periodAfter66,m.requestId,m.customer,m.by,m.reason]);if(teamTypes72.has('opening'))s.forEach(x=>values.unshift([range6.from||'قبل أول حركة','',x.team,x.product,'رصيد افتتاحي',x.opening,x.opening,'','','','']));if(teamTypes72.has('closing'))s.forEach(x=>values.push([range6.to||cairoDate66(now()),'',x.team,x.product,'الرصيد الحالي','',x.closing,'','','','']));return {headings,values}}
const teamStockOld72=VIEWS.teamStock6;VIEWS.teamStock6=function(){let html=teamStockOld72();const root=document.createElement('div');root.innerHTML=html;const summary=[...root.querySelectorAll('.card')].find(el=>el.querySelector('h3')?.textContent==='ملخص الفترة');if(summary)summary.innerHTML=`<h3>ملخص الفترة</h3><button class="green" onclick="exportTeamSection68('summary')">تصدير Excel</button>${table69(['الفريق','الصنف','الرصيد الافتتاحي','تعديل الافتتاحي','إضافات / تسويات','خصم / استهلاك','الرصيد الحالي'],teamSummaryRows72())}`;const detail=[...root.querySelectorAll('.card')].find(el=>el.querySelector('h3')?.textContent==='الحركات بالتاريخ والوقت');if(detail){const data=teamStatement72();detail.innerHTML=`<h3>الحركات بالتاريخ والوقت</h3><div class="filters72">${[['opening','رصيد افتتاحي'],['adjustment','تعديل رصيد افتتاحي'],['addition','إضافة / تسوية'],['consumption','استهلاك / حقن'],['closing','الرصيد الحالي']].map(([k,t])=>`<button aria-pressed="${teamTypes72.has(k)}" class="${teamTypes72.has(k)?'primary':'ghost'}" onclick="toggleTeamType72('${k}')">${t}</button>`).join('')}</div><button class="green" onclick="exportTeamSection68('movements')">تصدير Excel</button>${table69(data.headings,data.values)}`;}return root.innerHTML};
exportTeam6=function(){if(!isSayed6()||!validRange5(range6))return;const d=teamStatement72();downloadExcel5('FortiMune-Team-Statement',[{name:'ملخص الفترة',rows:[['الفريق','الصنف','الرصيد الافتتاحي','تعديل الافتتاحي','إضافات / تسويات','خصم / استهلاك','الرصيد الحالي'],...teamSummaryRows72()]},{name:'الحركات',rows:[d.headings,...d.values]},filterSheet69()])};
// One professional feedback card per committed operation.
appMessage=function(message,tone=messageTone(message)){let host=document.getElementById('appMessages');if(!host){host=document.createElement('div');host.id='appMessages';host.className='app-messages';document.body.append(host)}host.replaceChildren();const node=document.createElement('div');node.className='app-message '+tone;node.setAttribute('role',tone==='error'?'alert':'status');const title=tone==='success'?'تمت العملية بنجاح':tone==='warning'&&/بانتظار/.test(message)?'تم إرسال الطلب':tone==='warning'?'تنبيه':'تعذّر تنفيذ العملية';node.innerHTML=`<span class="message-symbol">${tone==='success'||/بانتظار/.test(message)?'✓':'❗'}</span><span class="message-copy"><b>${title}</b><small>${esc(message)}</small></span><button class="message-dismiss" aria-label="إغلاق">×</button>`;node.querySelector('button').onclick=()=>node.remove();host.append(node);setTimeout(()=>node.remove(),3000)};
const requestTable72=requestTable;requestTable=function(...args){const root=document.createElement('div');root.innerHTML=requestTable72(...args);root.querySelectorAll('.mobile-request-card').forEach(card=>{const id=card.querySelector('.mobile-request-top b')?.textContent?.trim(),r=(args[0]||[]).find(r=>r.id===id),el=card.querySelector('.mobile-request-products');if(r&&el)el.innerHTML=`<small>المنتجات والكميات</small>${(r.items||[]).map(i=>{const actual=r.actualItems?.find(x=>x.productId===i.productId)?.actualQty;return `<div class="product-row72"><b>${esc(i.productName||PRODUCTS.find(p=>p.id===i.productId)?.name)}</b><span><small>المطلوب</small><strong>${Number(i.requestedQty||0)}</strong></span>${actual!==undefined?`<span><small>الفعلي</small><strong>${Number(actual)}</strong></span>`:''}</div>`}).join('')}`});return root.innerHTML};
// Opening a known in-app notification is read-only and need not wait for background refresh.
openNotice64=async function(id){const n=currentNotifications().find(n=>n.id===id);if(!n?.requestId)return;if((db.financeRequests72||[]).some(r=>r.id===n.requestId)){closeNotificationPanel(true);go('financeRequests72');return;}const r=accessibleRequests().find(r=>r.id===n.requestId);if(r){closeNotificationPanel(true);handleBatchLink68(r.id);if(!cloudBusy&&!n.readAt)markNotificationRead(id);return;}const u=new URL(location.href);u.searchParams.set('request',n.requestId);u.searchParams.set('recipient',session.authUserId);history.replaceState(null,'',u);await handlePushLink62()};
const disableOld72=disablePush62;disablePush62=async function(show=true){try{return await disableOld72(show)}catch(e){if(!show){if(hasNative63()){await nativeCall63('disable');nativeBound63='';return;}const reg=await navigator.serviceWorker?.getRegistration('./');const sub=await reg?.pushManager?.getSubscription();if(sub){const removed=await sub.unsubscribe();if(!removed)throw e;}return;}throw e}};

let passwordResetBusy72=false;async function requestPasswordReset72(){if(passwordResetBusy72)return;const email=prompt('اكتب إيميل Outlook الرسمي المسجّل لحسابك')?.trim();if(!email)return;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return appMessage('اكتب إيميلًا صحيحًا','warning');if(!fortimuneSupabase)return appMessage('تعذّر الاتصال بخدمة تسجيل الدخول','error');passwordResetBusy72=true;try{const target=new URL('reset-password.html',location.href);target.search='';target.hash='';const {error}=await fortimuneSupabase.auth.resetPasswordForEmail(email,{redirectTo:target.href});if(error)throw error;appMessage('لو الإيميل مسجّل، هيوصلك رابط استعادة كلمة المرور. راجع البريد وJunk.','success')}catch(e){appMessage('تعذّر إرسال رابط الاستعادة: '+e.message,'error')}finally{passwordResetBusy72=false}}
const loginHost72=document.getElementById('login');if(loginHost72&&!document.getElementById('forgotPassword72')){const button=document.createElement('button');button.id='forgotPassword72';button.className='ghost';button.textContent='نسيت كلمة المرور؟';button.onclick=requestPasswordReset72;loginHost72.querySelector('form,.login-box,.login-card')?.append(button)||loginHost72.append(button);}
// Customer movement types are financial only; initial opening remains a separate selected row.
STANDARD62.splice(0,STANDARD62.length,'invoice','return','consumption','adjustment');typeLabels.adjustment='تعديل رصيد افتتاحي';delete typeLabels.settlement;movementFilter.types=[...STANDARD62];
selectedTypes62=function(){return Array.isArray(movementFilter.types)?movementFilter.types.filter(t=>STANDARD62.includes(t)):[...STANDARD62]};
const toggleOld72=toggleMovement62;toggleMovement62=function(type){if(type==='opening')return toggleOld72(type);if(type==='ALL'){movementFilter.types=[...STANDARD62];openingSelected69=true;}else{if(!STANDARD62.includes(type))return;const types=selectedTypes62();movementFilter.types=types.includes(type)?types.filter(t=>t!==type):[...types,type]}movementFilter.type='ALL';render()};
movementRows=function(){if(!financial71())return [];const customers=reportCustomers(),ids=new Set(customers.map(c=>c.id)),types=selectedTypes62(),groups=new Map();for(const m of db.movements||[]){if(!Number(m.change)||!ids.has(m.customerCode)||movementFilter.customers.length&&!movementFilter.customers.includes(m.customerCode))continue;const type=m.movementType==='opening_adjustment'||m.movementType==='adjustment'?'adjustment':m.returnId?'return':m.invoiceId?'invoice':m.requestId||m.movementType==='consumption'||m.movementType==='team_transfer'?'consumption':m.movementType;if(!types.includes(type))continue;const record=((type==='invoice'?db.invoices:type==='return'?db.returns:[])||[]).find(x=>x.id===(m.invoiceId||m.returnId));const date=String(record?.date||m.businessDate||cairoDate66(m.date)).slice(0,10);if(movementFilter.from&&date<movementFilter.from||movementFilter.to&&date>movementFilter.to)continue;const id=type==='consumption'?m.requestId||m.operationId||m.id:m.invoiceId||m.returnId||m.operationId||m.id;const key=[id,m.customerCode,type].join('|');if(!groups.has(key))groups.set(key,{id,date,type,customer:customers.find(c=>c.id===m.customerCode)?.name,region:customers.find(c=>c.id===m.customerCode)?.region,qty:{},details:[]});const row=groups.get(key);row.qty[m.productId]=(row.qty[m.productId]||0)+Number(m.change);row.details.push(m)}return [...groups.values()].sort((a,b)=>a.date.localeCompare(b.date)||String(a.details[0]?.date).localeCompare(String(b.details[0]?.date)))};
const finalMovement72=VIEWS.movement;VIEWS.movement=function(){const root=document.createElement('div');root.innerHTML=finalMovement72();root.querySelectorAll('.adjustment62').forEach(el=>el.remove());const body=root.querySelector('.v5-table tbody');if(body){const ending=[...body.querySelectorAll('.movement-ending69')],regular=[...body.querySelectorAll('tr:not(.movement-ending69)')];const parse=el=>{const t=el.querySelector('td')?.textContent||'';const m=t.match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?m[3]+'-'+m[2]+'-'+m[1]:t};regular.sort((a,b)=>parse(a).localeCompare(parse(b)));body.replaceChildren(...regular,...ending)}root.querySelectorAll('p.muted').forEach(el=>{if(/تُخصم عند التسوية/.test(el.textContent))el.textContent='الرصيد النهائي يشمل جميع الحركات حتى نهاية الفترة. الاستهلاك يُخصم مرة واحدة عند اعتماد التنفيذ.'});return root.innerHTML};
const exportCustomer72=exportMovement5;exportMovement5=function(){const original=downloadExcel5;downloadExcel5=function(name,sheets){for(const sheet of sheets){if(sheet.name==='حركة العملاء'||sheet.name==='تفاصيل الأرصدة'){const head=sheet.rows[0];sheet.rows=[head,...sheet.rows.slice(1).sort((a,b)=>String(a[0]).localeCompare(String(b[0])))];sheet.styles=undefined;}}return original(name,sheets)};try{return exportCustomer72()}finally{downloadExcel5=original}};
VIEWS.teamMovement69=()=>isSayed6()?VIEWS.teamStock6():'';VIEWS.teamBalances69=()=>isSayed6()?VIEWS.teamStock6():'';
const finalRequests72=VIEWS.requests66;VIEWS.requests66=function(){return finalRequests72().replaceAll('اعتماد تقارير التنفيذ','اعتماد التنفيذ')};
const disableFinal72=disablePush62;disablePush62=async function(show=true){if(!show&&session?.authUserId&&fortimuneSupabase){let endpoint='';if(hasNative63()){const device=await nativeCall63('disable');endpoint=device.subscriptionId?'onesignal:'+device.subscriptionId:'';nativeBound63='';}else{const reg=await navigator.serviceWorker?.getRegistration('./');const sub=await reg?.pushManager?.getSubscription();endpoint=sub?.endpoint||'';}if(endpoint){const {error}=await fortimuneSupabase.rpc('fortimune_push_unsubscribe72',{device_endpoint:endpoint});if(error){try{await pushAPI62({action:'unsubscribe',endpoint})}catch(e){/* Device is already locally opted out; recipient checks prevent cross-account delivery. */}}}return disableFinal72(false)}return disableFinal72(show)};
const teamSummaryOld72=teamSummary66;teamSummary66=function(){return teamSummaryOld72().map(s=>{const rows=teamLedger6().filter(m=>m.team===s.team&&m.productId===s.productId&&(!range6.from||ledgerDate66(m)>=range6.from)&&(!range6.to||ledgerDate66(m)<=range6.to)),isConsumption=m=>/consumption/.test(m.kind||'')||Number(m.change)<0&&!/opening|settlement/.test(m.kind||''),debits=-rows.filter(isConsumption).reduce((n,m)=>n+Number(m.change||0),0),additions=rows.filter(m=>!isConsumption(m)&&!/opening/.test(m.kind||'')).reduce((n,m)=>n+Number(m.change||0),0);return {...s,additions,settlements:0,debits}})};
teamCategory72=function(m){return /opening/.test(m.kind||'')?'adjustment':/consumption/.test(m.kind||'')||Number(m.change)<0&&!/settlement/.test(m.kind||'')?'consumption':'addition'};
const teamKindFinal72=teamKind66;teamKind66=function(m){return m.kind==='team_consumption_revision72'?'استهلاك / حقن — تصحيح تقرير':teamKindFinal72(m)};

const deficitRowsOld72=deficitRows71;deficitRows71=function(kind){return deficitRowsOld72(kind).filter(d=>!deficitFilter71.employee||deficitFilter71.employee==='ALL'||db.requests.find(r=>r.id===d.requestId)?.createdByEmployeeId===deficitFilter71.employee)};
const deficitViewFinal72=deficitPage71;deficitPage71=function(kind){const root=document.createElement('div');root.innerHTML=deficitViewFinal72(kind);const employees=[...new Map(accessibleRequests().map(r=>[r.createdByEmployeeId,r.createdBy||r.requestedByName||r.createdByEmployeeId])).entries()].filter(([id])=>id);if(kind==='customer')root.querySelector('.request-form-grid')?.insertAdjacentHTML('beforeend',`<div><label>الزميل صاحب الطلب</label><select onchange="setDeficit71('employee',this.value)"><option value="ALL">كل الزملاء المتاحين</option>${employees.map(([id,name])=>`<option value="${esc(id)}" ${deficitFilter71.employee===id?'selected':''}>${esc(name)}</option>`).join('')}</select></div>`);return root.innerHTML};
const noticeOld72=openNotice64;openNotice64=async function(id){const n=currentNotifications().find(n=>n.id===id);if(!n)return;if((db.customerRequests66||[]).some(r=>r.id===n.requestId)){closeNotificationPanel(true);go('customerApprovals66');return;}if((db.customerChanges70||[]).some(r=>r.id===n.requestId)){closeNotificationPanel(true);go('customerChanges70');return;}return noticeOld72(id)};
// A visible form instead of the browser's password recovery prompt.
const sendRecovery72=requestPasswordReset72;requestPasswordReset72=function(){if(document.getElementById('recoveryDialog72'))return;const el=document.createElement('div');el.id='recoveryDialog72';el.className='app-confirm-overlay';el.dir='rtl';el.innerHTML=`<section class="app-confirm" role="dialog" aria-modal="true"><h3>استعادة كلمة المرور</h3><p>هنرسل رابط الاستعادة إلى إيميل Outlook الرسمي المسجّل.</p><label for="recoveryEmail72">الإيميل الرسمي</label><input id="recoveryEmail72" type="email" autocomplete="email" dir="ltr"><div class="actions"><button class="primary" id="sendRecovery72">إرسال الرابط</button><button class="ghost" onclick="document.getElementById('recoveryDialog72').remove()">إلغاء</button></div></section>`;document.body.append(el);el.querySelector('input').focus();el.querySelector('#sendRecovery72').onclick=async()=>{const email=el.querySelector('input').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return appMessage('اكتب إيميلًا صحيحًا','warning');const button=el.querySelector('#sendRecovery72');button.disabled=true;try{if(!fortimuneSupabase)throw Error('تعذّر الاتصال');const target=new URL('reset-password.html',location.href);target.search='';target.hash='';const {error}=await fortimuneSupabase.auth.resetPasswordForEmail(email,{redirectTo:target.href});if(error)throw error;el.remove();appMessage('لو الإيميل مسجّل، هيوصلك رابط الاستعادة. راجع البريد وJunk.','success')}catch(e){appMessage('تعذّر إرسال الرابط: '+e.message,'error')}finally{button.disabled=false}}};document.getElementById('forgotPassword72').onclick=()=>requestPasswordReset72();
const teamStockFinal72=VIEWS.teamStock6;VIEWS.teamStock6=function(){const root=document.createElement('div');root.innerHTML=teamStockFinal72();root.querySelectorAll('table tbody tr').forEach(tr=>{if([...tr.children].some(td=>td.textContent==='الرصيد الحالي'))tr.classList.add('movement-ending69');tr.querySelectorAll('td').forEach(td=>{if(/^[-−]\d+(\.\d+)?$/.test(td.textContent.trim()))td.classList.add('negative6')})});return root.innerHTML};
const notificationTypeFinal72=notificationType;notificationType=function(n){return /فاتورة بيع \/ مرتجع.*مطلوب الموافقة/.test(n.title||'')?'approval':notificationTypeFinal72(n)};
const noticeDetailsFinal72=notificationDetails53;notificationDetails53=function(n){const r=(db.financeRequests72||[]).find(r=>r.id===n.requestId);return r?`<p>${esc(r.customerName)} • ${esc(r.createdBy)}</p>${table69(['الصنف','الكمية'],(r.payload?.items||[]).map(i=>[i.productName||i.productId,i.qty]))}`:noticeDetailsFinal72(n)};
const dashCommitted72=dashData61;dashData61=function(){const d=dashCommitted72();d.movements=d.movements.filter(m=>{if(m.type!=='consumption')return true;const r=db.requests.find(r=>r.id===m.id)||(m.details||[]).map(x=>db.requests.find(r=>r.id===x.requestId)).find(Boolean);return !r||!!r.balanceDeductedAt||!r.flow71&&!r.flow72&&r.settlementModel68!=='on_settlement'});return d};
